// Mock data store — simulating backend responses
import { Colors } from '../theme';

export const mockPackages = [
  {
    id: 'p1',
    title: 'Hunza Valley Luxury Retreat',
    agency: 'Northern Trails',
    agencyId: 'a2',
    destination: 'Hunza, Gilgit-Baltistan',
    price: 85000,
    duration: 7,
    rating: 4.8,
    reviewCount: 124,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDE9xajh-roQLam_xXLRv2C2zcJ_4OwQuMyoFJlbVdn27acZZanRhSr__1YZKJy17-voIPaRPlBOmjFm91qOHJpn-EpCWrPAon_vakVR96MM5Tetd8a6nD1OWMKwipM6SYJCPKr2_A_h9_Id4f5hpqAdS6wlTRmnmWcCB2PFFs99MTZHG1AeUxYoY5zUaKPxcuh-ptQ_jahepZTpcrh-bNL6b5ziOWgOa2p21vFXr1kfmdjLMEeYt0VlQyNhjAp8vMqXPKlD2vmxbmJ',
    tag: 'Featured',
    tagColor: Colors.plum,
    description: 'Experience the breathtaking beauty of Hunza Valley with our premium 7-day retreat. Includes luxury accommodation, guided treks to Eagle\'s Nest, Baltit Fort visits, and authentic Hunzai cuisine.',
    highlights: ['Luxury mountain lodge', 'Eagle\'s Nest sunset view', 'Baltit Fort guided tour', 'Karimabad bazaar visit', 'Attabad Lake boat ride'],
    inclusions: ['Return transport', 'All meals', 'Professional guide', '3-star+ lodging'],
    difficulty: 'Easy–Moderate',
    groupSize: '4–12 people',
  },
  {
    id: 'p2',
    title: 'K2 Base Camp Trek',
    agency: 'Peak Adventures',
    agencyId: 'a1',
    destination: 'Skardu, Gilgit-Baltistan',
    price: 125000,
    duration: 14,
    rating: 4.9,
    reviewCount: 87,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAr9N4r2pQIG8XJBvWb16F6nvhEXPgYZWTQ4Hru5477Lyf6_bv5TFmbZsowTHQc2Z7em1tZ_oDLZOxdwIdVbNFbMccFtMgQ-bkLP0jrFZ6_M0QEEMVWIKIhzd4TmSHAZr-wdKfi7CiSb6Dw7nlNWAST-oiM2bxZPvZj1__Z_D7KDbjWwp5Xei7qDMxGvq_I_WgKu9z27buIpPiUJud-6ZxTXqHQmHCSGvOBjEUmPqv-D9CszcFkRTrTP8VoSeiOilDAS_0lUPvGnbNv',
    tag: 'Adventure',
    tagColor: Colors.primary,
    description: 'The ultimate mountaineering challenge — trek to the base of the world\'s second highest peak. A once-in-a-lifetime journey through the Karakoram range.',
    highlights: ['K2 Base Camp at 5,100m', 'Concordia viewpoint', 'Baltoro Glacier crossing', 'Gasherbrum massif views'],
    inclusions: ['Full porter & guide team', 'All camping gear', 'Meals on trail', 'Permits & fees'],
    difficulty: 'Challenging',
    groupSize: '2–8 people',
  },
  {
    id: 'p3',
    title: 'Swat Valley Spring Bloom',
    agency: 'Odyssey Travels',
    agencyId: 'a3',
    destination: 'Swat, KPK',
    price: 32000,
    duration: 3,
    rating: 4.6,
    reviewCount: 203,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDE9xajh-roQLam_xXLRv2C2zcJ_4OwQuMyoFJlbVdn27acZZanRhSr__1YZKJy17-voIPaRPlBOmjFm91qOHJpn-EpCWrPAon_vakVR96MM5Tetd8a6nD1OWMKwipM6SYJCPKr2_A_h9_Id4f5hpqAdS6wlTRmnmWcCB2PFFs99MTZHG1AeUxYoY5zUaKPxcuh-ptQ_jahepZTpcrh-bNL6b5ziOWgOa2p21vFXr1kfmdjLMEeYt0VlQyNhjAp8vMqXPKlD2vmxbmJ',
    tag: 'Weekend',
    tagColor: Colors.success,
    description: 'A refreshing 3-day escape to the lush green valleys of Swat during peak spring season. Cherry blossoms, waterfalls, and mountain villages await.',
    highlights: ['Malam Jabba', 'Mahodand Lake', 'Kalam Valley', 'Local market experience'],
    inclusions: ['Transport from Islamabad', 'Hotel stay', 'Breakfast & dinner'],
    difficulty: 'Easy',
    groupSize: '6–20 people',
  },
  {
    id: 'p4',
    title: 'Maldives Luxury Escape',
    agency: 'Blue Horizon Co.',
    agencyId: 'a4',
    destination: 'Maldives',
    price: 320000,
    duration: 5,
    rating: 4.9,
    reviewCount: 56,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCLcOL5_Md5WsCR1-4sEBqmH7uckkSerjpIzQ_5ggTe_VGVYv9kcvUERbTzSArXBi89ouiKLq2Vxz_6EN6MKfnfYYalUSqFgrYhR7dsouwmcoh5k3Jty8YDZnahU57q6RS8oXOXfkcNUN6cDUfgYhIZi0NDg15ZxfSpfZUpDv4tFQUQYXeg7iyHhEJ6GpjeYhtwfNqqBjbjdm69kd7IG1K2ep1hT6xC3l3GLGDvAs2Ymj0OBMurinZ4fFRbm2rzh7gwuZUSjrbQ8p3x',
    tag: 'Luxury',
    tagColor: Colors.tertiary,
    description: 'Indulge in 5 nights of pure luxury at a private overwater bungalow in the Maldives. Crystal clear lagoons, world-class dining, and unparalleled serenity.',
    highlights: ['Overwater bungalow', 'Private beach access', 'Snorkeling & diving', 'Sunset dolphin cruise'],
    inclusions: ['Business class flights', 'All-inclusive stay', 'Seaplane transfers'],
    difficulty: 'Easy',
    groupSize: '2 people (couples)',
  },
  {
    id: 'p5',
    title: 'Fairy Meadows Trek',
    agency: 'Northern Trails',
    agencyId: 'a2',
    destination: 'Nanga Parbat Base, GB',
    price: 45000,
    duration: 4,
    rating: 4.7,
    reviewCount: 142,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAr9N4r2pQIG8XJBvWb16F6nvhEXPgYZWTQ4Hru5477Lyf6_bv5TFmbZsowTHQc2Z7em1tZ_oDLZOxdwIdVbNFbMccFtMgQ-bkLP0jrFZ6_M0QEEMVWIKIhzd4TmSHAZr-wdKfi7CiSb6Dw7nlNWAST-oiM2bxZPvZj1__Z_D7KDbjWwp5Xei7qDMxGvq_I_WgKu9z27buIpPiUJud-6ZxTXqHQmHCSGvOBjEUmPqv-D9CszcFkRTrTP8VoSeiOilDAS_0lUPvGnbNv',
    tag: 'Trek',
    tagColor: Colors.warning,
    description: 'Trek through one of Pakistan\'s most legendary meadows with direct views of Nanga Parbat, the 9th highest mountain in the world.',
    highlights: ['Fairy Meadows camp', 'Nanga Parbat sunrise', 'Beyal Base Camp', 'Stargazing night'],
    inclusions: ['Jeep from Raikot Bridge', 'Camping gear', 'Local guide', 'Meals'],
    difficulty: 'Moderate',
    groupSize: '4–15 people',
  },
];

export const mockAgencyStats = {
  totalPackages: 8,
  totalBookings: 142,
  pendingEnquiries: 6,
  rating: 4.8,
  earnings: 2840000,
};

export const mockConversations = [
  {
    id: 'c1',
    traveler: 'Ahmed Hassan',
    travelerInitials: 'AH',
    agency: 'Odyssey Travels',
    agencyInitials: 'OT',
    package: 'Hunza Valley Trek',
    lastMsg: 'We have updated the itinerary for your...',
    time: '10:32 AM',
    unread: 2,
  },
  {
    id: 'c2',
    traveler: 'Sara Khan',
    travelerInitials: 'SK',
    agency: 'Aurora Travels',
    agencyInitials: 'AT',
    package: 'The Cycladic Sanctuary',
    lastMsg: 'The private villa in Santorini is available...',
    time: 'Yesterday',
    unread: 0,
  },
  {
    id: 'c3',
    traveler: 'Usman Tariq',
    travelerInitials: 'UT',
    agency: 'Nomadic Luxury',
    agencyInitials: 'NL',
    package: 'Heritage & Modernity',
    lastMsg: 'Would you like to add the spa package?',
    time: 'Mon',
    unread: 0,
  },
  {
    id: 'c4',
    traveler: 'Maria Siddiqui',
    travelerInitials: 'MS',
    agency: 'Amalfi Curators',
    agencyInitials: 'AC',
    package: 'Coastline Modernism',
    lastMsg: 'Checking on those flight upgrades now.',
    time: 'Dec 12',
    unread: 0,
  },
  {
    id: 'c5',
    traveler: 'Zainab Bibi',
    travelerInitials: 'ZB',
    agency: 'Desert Escape',
    agencyInitials: 'DE',
    package: 'Namibian Solitude',
    lastMsg: 'Welcome back! How was your trip?',
    time: 'Nov 28',
    unread: 0,
  },
];

export const mockWishlist = ['p1', 'p3', 'p5'];
