// Mock data store — simulating backend responses
import { Colors } from '../theme';

export const mockPackages = [
  {
    id: 'p1',
    title: 'Hunza Valley Luxury Retreat',
    agency: 'Northern Trails',
    agencyId: 'a2',
    destination: 'Hunza, Gilgit-Baltistan',
    price: 85000,
    duration: 7,
    rating: 4.8,
    reviewCount: 124,
    image: 'https://lh3.googleusercontent.com/aida/ADBb0uigouzg6XqCbiRm8DdvWkha3BTvxc-cQuf13paZdSSqs-_Q_k8tupor81o6BP3fP5ZZbg3NeFPP9zxX5Juu93UAHYrtiCRjTuLQs2yFx393Tj69XECdUYwISFgNoD6uFmDdENnwc48OoRLjpuXz8q4TpBrJFl3I0AljsPSKTnPrVXClBxMrwv-Hm_WuwZKBxcUtyrNsvs84nL2Kvth0D9Yv92-dSDUud0ZOeuVMOyeKv1s8HsWTmDaMIHQG',
    tag: 'Featured',
    tagColor: Colors.plum,
    description: 'Experience the breathtaking beauty of Hunza Valley with our premium 7-day retreat. Includes luxury accommodation, guided treks to Eagle\'s Nest, Baltit Fort visits, and authentic Hunzai cuisine.',
    highlights: ['Luxury mountain lodge', 'Eagle\'s Nest sunset view', 'Baltit Fort guided tour', 'Karimabad bazaar visit', 'Attabad Lake boat ride'],
    inclusions: ['Return transport', 'All meals', 'Professional guide', '3-star+ lodging'],
    difficulty: 'Easy–Moderate',
    groupSize: '4–12 people',
  },
  {
    id: 'p2',
    title: 'K2 Base Camp Trek',
    agency: 'Peak Adventures',
    agencyId: 'a1',
    destination: 'Skardu, Gilgit-Baltistan',
    price: 125000,
    duration: 14,
    rating: 4.9,
    reviewCount: 87,
    image: 'https://lh3.googleusercontent.com/aida/ADBb0uj6e2QjTZZzEjaae4aKWwfM_g4Xv0drswd8_kYCPyKV4T9bCMBDfEg5xfqlYViq3WV3KmBkAKNWPXx9cxa_-dGbTeX1Tsu_WDsdAuyDnaHEoOrDbQdSUJsJAKzGyTA1Yyb76hssBWB5jwprDKki6fOtR5lfuHKyX2ZBgzJallXitXOtCC0VOAqoSFYbp4s3zomcy8WrYlT4--OWh_wH-NjNiZEJZn2AYCtwUvD_TO5gzjM9BETPuhHia-OR',
    tag: 'Adventure',
    tagColor: Colors.primary,
    description: 'The ultimate mountaineering challenge — trek to the base of the world\'s second highest peak. A once-in-a-lifetime journey through the Karakoram range.',
    highlights: ['K2 Base Camp at 5,100m', 'Concordia viewpoint', 'Baltoro Glacier crossing', 'Gasherbrum massif views'],
    inclusions: ['Full porter & guide team', 'All camping gear', 'Meals on trail', 'Permits & fees'],
    difficulty: 'Challenging',
    groupSize: '2–8 people',
  },
  {
    id: 'p3',
    title: 'Swat Valley Spring Bloom',
    agency: 'Odyssey Travels',
    agencyId: 'a3',
    destination: 'Swat, KPK',
    price: 32000,
    duration: 3,
    rating: 4.6,
    reviewCount: 203,
    image: 'https://lh3.googleusercontent.com/aida/ADBb0uhVp21Tcu5sRl3Q1so0_zOyOk0gzgKp0c6qEcQbOfpHOr0VxacorPwhT-0w9VbGqVrgMME9_YMNpng6cv4QDZd_szhE_BNe81mJwKCD1LiuVxPJWPqIM0BnarYhtMXLmz3bQblP03BlggB8DTvujh0dbeDh40V5Wp8GOXLrCP8f_YLnBiZ_4emQkIrOupULz9OqaKQzoXoQbs0KgvtthhTgojziq6myQOmkJMck-seMxzGy-p9fCAoUCwVP',
    tag: 'Weekend',
    tagColor: Colors.success,
    description: 'A refreshing 3-day escape to the lush green valleys of Swat during peak spring season. Cherry blossoms, waterfalls, and mountain villages await.',
    highlights: ['Malam Jabba', 'Mahodand Lake', 'Kalam Valley', 'Local market experience'],
    inclusions: ['Transport from Islamabad', 'Hotel stay', 'Breakfast & dinner'],
    difficulty: 'Easy',
    groupSize: '6–20 people',
  },
  {
    id: 'p4',
    title: 'Maldives Luxury Escape',
    agency: 'Blue Horizon Co.',
    agencyId: 'a4',
    destination: 'Maldives',
    price: 320000,
    duration: 5,
    rating: 4.9,
    reviewCount: 56,
    image: 'https://lh3.googleusercontent.com/aida/ADBb0uhRUcZ0jHyVUp9pksr3CzWodUX5aGySqCr18hDntC6L5UxdJ5c4ntLDfjeRElfdmfqpqmMHWz9uH8wfoLSWaeLzy3nfgcEH_4BsBlzqhlU3PHIRQENXVIcToes8IUNqMMdOrGoTUimSotvAwTLQ-aasMI-kKD8U-PiDZLne7rPL9KkXiQGVdXiUeIOp6YBc45k8pTM9neoGXvR_cUeMhJvdnGkwDKWG6wdDxFSUCsLpRe0by0AjeTsgMYkj',
    tag: 'Luxury',
    tagColor: Colors.tertiary,
    description: 'Indulge in 5 nights of pure luxury at a private overwater bungalow in the Maldives. Crystal clear lagoons, world-class dining, and unparalleled serenity.',
    highlights: ['Overwater bungalow', 'Private beach access', 'Snorkeling & diving', 'Sunset dolphin cruise'],
    inclusions: ['Business class flights', 'All-inclusive stay', 'Seaplane transfers'],
    difficulty: 'Easy',
    groupSize: '2 people (couples)',
  },
  {
    id: 'p5',
    title: 'Fairy Meadows Trek',
    agency: 'Northern Trails',
    agencyId: 'a2',
    destination: 'Nanga Parbat Base, GB',
    price: 45000,
    duration: 4,
    rating: 4.7,
    reviewCount: 142,
    image: 'https://lh3.googleusercontent.com/aida/ADBb0uiU4AoP7x3Q1yeWzKscxvZcypwTMuqyJA15kmCxWxL_8HoHOZ4XhF0MJh6ty_kP91XNtirh-MEYVK3YvvvyA9xG-A6rSsoWTue-RQR8PZr3pT2DcggEUw4AW1-1HijbJ0HMA5aJTgGW0VMTGO4IBWUeTS4PYZREsN9cAvRjdD6Lb6edkr1cak34_JAxSeNsdOU87cDNOeOAJV9zVt9k9sA5imbHkA1fzmGW2SstIbC1AmVPyFxF3QHibr-y',
    tag: 'Trek',
    tagColor: Colors.warning,
    description: 'Trek through one of Pakistan\'s most legendary meadows with direct views of Nanga Parbat, the 9th highest mountain in the world.',
    highlights: ['Fairy Meadows camp', 'Nanga Parbat sunrise', 'Beyal Base Camp', 'Stargazing night'],
    inclusions: ['Jeep from Raikot Bridge', 'Camping gear', 'Local guide', 'Meals'],
    difficulty: 'Moderate',
    groupSize: '4–15 people',
  },
];

export const mockAgencyStats = {
  totalPackages: 8,
  totalBookings: 142,
  pendingEnquiries: 6,
  rating: 4.8,
  earnings: 2840000,
};

export const mockConversations = [
  { id: 'c1', traveler: 'Ahmed Hassan',   initials: 'AH', package: 'K2 Base Camp Trek',     lastMsg: 'Is there a group discount?',        time: '10m', unread: 2 },
  { id: 'c2', traveler: 'Sara Khan',      initials: 'SK', package: 'Hunza Valley Retreat',  lastMsg: 'Please confirm my booking.',         time: '1h',  unread: 0 },
  { id: 'c3', traveler: 'Usman Tariq',    initials: 'UT', package: 'Swat Valley Spring',    lastMsg: 'What is included in the price?',    time: '3h',  unread: 1 },
  { id: 'c4', traveler: 'Maria Siddiqui', initials: 'MS', package: 'Fairy Meadows Trek',    lastMsg: 'Can I cancel for a full refund?',   time: 'Yesterday', unread: 0 },
];

export const mockWishlist = ['p1', 'p3', 'p5'];
